In [ ]:
import numpy as np
import pandas as pd
from scipy.io import loadmat
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Load the .mat file
data = loadmat(r"C:\Users\Shampa Barman\Music\Matlab_cancer.mat")

# Extract features and labels
X = data['x']
y = data['t']
# Convert to DataFrame for easier manipulation (if needed)
# X = pd.DataFrame(X)
# y = pd.DataFrame(y)

In [ ]:
X

array([[0.46290091, 0.37056537, 0.46155037, ..., 0.58252595, 0.63768441,
        0.52859127],
       [0.40673611, 0.30643103, 0.27898015, ..., 0.4498    , 0.49972172,
        0.45315089],
       [0.30621525, 0.23971475, 0.20660846, ..., 0.34488742, 0.33761557,
        0.41943002],
       ...,
       [0.08009822, 0.23816822, 0.23361855, ..., 0.15979104, 0.13400809,
        0.1597645 ],
       [0.14462108, 0.18637254, 0.17546801, ..., 0.10701832, 0.1389127 ,
        0.29903768],
       [0.10640488, 0.12637318, 0.0999025 , ..., 0.17790702, 0.177601  ,
        0.17012326]])

In [ ]:
y

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [ ]:
print(X.shape,y.shape)

(100, 216) (2, 216)


In [ ]:
print(type(X))

<class 'numpy.ndarray'>


In [ ]:
df=pd.DataFrame(X)
df

0         1         2         3         4         5         6    \
0   0.462901  0.370565  0.461550  0.375149  0.113849  0.233627  0.566678   
1   0.406736  0.306431  0.278980  0.287317  0.108411  0.117294  0.470354   
2   0.306215  0.239715  0.206608  0.241130  0.086275  0.059205  0.377392   
3   0.488105  0.476358  0.744342  0.426810  0.219954  0.284276  0.669022   
4   0.175169  0.175900  0.152133  0.205859  0.050794  0.047048  0.317999   
..       ...       ...       ...       ...       ...       ...       ...   
95  0.102007  0.163589  0.108145  0.129792  0.108191  0.134398  0.182019   
96  1.669069  2.232187  2.142075  1.951741  3.917728  3.067101  0.692836   
97  0.080098  0.238168  0.233619  0.168771  0.246519  0.138255  0.049109   
98  0.144621  0.186373  0.175468  0.136800  0.079653  0.055678  0.314902   
99  0.106405  0.126373  0.099903  0.116469  0.012750  0.123548  0.136918   

         7         8         9    ...       206       207       208       209  \
0   0.627662  0.381812  0.455935  ...  0.518304  0.679998  0.861971  0.891380   
1   0.523693  0.247376  0.386352  ...  0.362863  0.612171  0.716505  0.804140   
2   0.429015  0.203156  0.284720  ...  0.215489  0.502485  0.593316  0.648416   
3   0.727860  0.543950  0.509489  ...  0.587237  0.695925  0.980418  0.931691   
4   0.318464  0.122031  0.158107  ...  0.133816  0.360841  0.480872  0.468973   
..       ...       ...       ...  ...       ...       ...       ...       ...   
95  0.124871  0.097083  0.155205  ...  0.104120  0.126577  0.230165  0.202313   
96  1.214623  1.396490  1.293816  ...  1.839021  0.822627  0.194489  0.544723   
97  0.076610  0.271379  0.064827  ...  0.178631  0.075754  0.019391  0.100852   
98  0.213265  0.158562  0.079212  ...  0.097148  0.162369  0.448877  0.295088   
99  0.307412  0.078940  0.120925  ...  0.084328  0.198927  0.302474  0.353438   

         210       211       212       213       214       215  
0   0.728070  0.712350  0.442507  0.582526  0.637684  0.528591  
1   0.631755  0.577324  0.378966  0.449800  0.499722  0.453151  
2   0.551587  0.458963  0.309647  0.344887  0.337616  0.419430  
3   0.811608  0.824525  0.579831  0.648084  0.690683  0.608099  
4   0.478606  0.327974  0.247915  0.249213  0.226858  0.348519  
..       ...       ...       ...       ...       ...       ...  
95  0.147342  0.126562  0.133148  0.124520  0.144252  0.102442  
96  0.923899  1.114880  1.785518  0.996573  1.059562  1.750116  
97  0.145998  0.132422  0.185799  0.159791  0.134008  0.159765  
98  0.220984  0.195418  0.161314  0.107018  0.138913  0.299038  
99  0.113650  0.223841  0.178209  0.177907  0.177601  0.170123  

[100 rows x 216 columns]

In [ ]:
df=pd.DataFrame(y)
df

0    1    2    3    4    5    6    7    8    9    ...  206  207  208  209  \
0    1    1    1    1    1    1    1    1    1    1  ...    0    0    0    0   
1    0    0    0    0    0    0    0    0    0    0  ...    1    1    1    1   

   210  211  212  213  214  215  
0    0    0    0    0    0    0  
1    1    1    1    1    1    1  

[2 rows x 216 columns]

In [ ]:
 #Transpose DataFrame X
X_transposed = X.T
print("\nTransposed DataFrame X:")
print(X_transposed)



Transposed DataFrame X:
[[0.46290091 0.40673611 0.30621525 ... 0.08009822 0.14462108 0.10640488]
 [0.37056537 0.30643103 0.23971475 ... 0.23816822 0.18637254 0.12637318]
 [0.46155037 0.27898015 0.20660846 ... 0.23361855 0.17546801 0.0999025 ]
 ...
 [0.58252595 0.4498     0.34488742 ... 0.15979104 0.10701832 0.17790702]
 [0.63768441 0.49972172 0.33761557 ... 0.13400809 0.1389127  0.177601  ]
 [0.52859127 0.45315089 0.41943002 ... 0.1597645  0.29903768 0.17012326]]


In [ ]:
# Transpose DataFrame y
y_transposed = y.T
print("\nTransposed DataFrame y:")
print(y_transposed)


Transposed DataFrame y:
[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [

In [ ]:
print(X_transposed.shape,y_transposed.shape)

(216, 100) (216, 2)


In [ ]:
# Ensure indices match (usually true by default)
assert len(X_transposed) == len(y_transposed), "Length of X and y must match"

In [ ]:
dfy=pd.DataFrame(y_transposed)
dfy

0  1
0    1  0
1    1  0
2    1  0
3    1  0
4    1  0
..  .. ..
211  0  1
212  0  1
213  0  1
214  0  1
215  0  1

[216 rows x 2 columns]

In [ ]:
# Define a mapping function to convert binary pair to label
def map_binary_to_label(row):
    if row[0] == 0 and row[1] == 1:
        return 'Normal'
    elif row[0] == 1 and row[1] == 0:
        return 'Cancer'
    else:
        return 'Unknown'  # In case there are any other combinations

# Apply the function to each row and create a new column
dfy['N/C'] = dfy.apply(map_binary_to_label, axis=1)

print("\nDataFrame with Target Labels:")
print(dfy[['N/C']])


DataFrame with Target Labels:
        N/C
0    Cancer
1    Cancer
2    Cancer
3    Cancer
4    Cancer
..      ...
211  Normal
212  Normal
213  Normal
214  Normal
215  Normal

[216 rows x 1 columns]


In [ ]:
y=dfy[['N/C']]
y

N/C
0    Cancer
1    Cancer
2    Cancer
3    Cancer
4    Cancer
..      ...
211  Normal
212  Normal
213  Normal
214  Normal
215  Normal

[216 rows x 1 columns]

In [ ]:
y.value_counts() # label is not skewed

N/C_Normal
False         121
True           95
Name: count, dtype: int64

In [ ]:
y = pd.get_dummies(y, drop_first=True)
y.sample(5) # cancer --> 1 and normal --> 0

N/C_Normal
170           1
11            0
107           0
177           1
144           1

In [ ]:
y.dtypes

N/C_Normal    int32
dtype: object

N/C_Normal
183           1
147           1
80            0
45            0
58            0

N/C_Normal    int32
dtype: object

In [ ]:
X=(X_transposed)
X

array([[0.46290091, 0.40673611, 0.30621525, ..., 0.08009822, 0.14462108,
        0.10640488],
       [0.37056537, 0.30643103, 0.23971475, ..., 0.23816822, 0.18637254,
        0.12637318],
       [0.46155037, 0.27898015, 0.20660846, ..., 0.23361855, 0.17546801,
        0.0999025 ],
       ...,
       [0.58252595, 0.4498    , 0.34488742, ..., 0.15979104, 0.10701832,
        0.17790702],
       [0.63768441, 0.49972172, 0.33761557, ..., 0.13400809, 0.1389127 ,
        0.177601  ],
       [0.52859127, 0.45315089, 0.41943002, ..., 0.1597645 , 0.29903768,
        0.17012326]])

In [ ]:
X=pd.DataFrame(X_transposed)
X.sample(5)

0         1         2         3         4         5         6   \
150  0.599289  0.482335  0.396989  0.702876  0.304241  0.565064  0.723684   
159  0.530682  0.461087  0.369516  0.559975  0.308552  0.466116  0.503401   
22   0.582982  0.525321  0.424064  0.628094  0.330333  0.346046  0.528821   
27   0.381793  0.230879  0.130748  0.509708  0.094454  0.325208  0.461303   
70   0.452141  0.338447  0.251799  0.603645  0.174594  0.462206  0.613532   

           7         8         9   ...        90        91        92  \
150  0.379430  2.066268  2.401903  ...  0.250892  0.200062  0.030813   
159  0.384273  1.781109  2.105188  ...  0.016224  0.015783  0.024919   
22   0.209523  1.490518  1.815130  ...  0.618003  0.491413  0.163517   
27   0.181154  1.562314  1.840856  ...  0.438801  0.310663  0.153057   
70   0.341824  1.638791  1.960121  ...  1.352629  1.123992  0.383766   

           93        94        95        96        97        98        99  
150  1.198251  0.065749  0.193455  0.788271  0.100722  0.271118  0.206702  
159  1.821541  0.113514  0.179858  0.663810  0.017385  0.176135  0.231803  
22   0.820039  0.118659  0.155546  1.089815  0.160775  0.145984  0.138592  
27   0.530887  0.149323  0.144372  1.416809  0.180572  0.190383  0.070508  
70   0.845236  0.104525  0.108428  1.787994  0.184485  0.128869  0.247267  

[5 rows x 100 columns]

In [ ]:
print(X.shape,y.shape)

(216, 100) (216, 1)


In [ ]:
# Combine DataFrames
df = pd.concat([X, y], axis=1)

#print("Combined DataFrame:")
print(df)

            0         1         2         3         4         5         6  \
0    0.462901  0.406736  0.306215  0.488105  0.175169  0.356551  0.439552   
1    0.370565  0.306431  0.239715  0.476358  0.175900  0.353762  0.476071   
2    0.461550  0.278980  0.206608  0.744342  0.152133  0.247645  0.304292   
3    0.375149  0.287317  0.241130  0.426810  0.205859  0.208770  0.283752   
4    0.113849  0.108411  0.086275  0.219954  0.050794  0.116163  0.188402   
..        ...       ...       ...       ...       ...       ...       ...   
211  0.712350  0.577324  0.458963  0.824525  0.327974  0.552057  0.708814   
212  0.442507  0.378966  0.309647  0.579831  0.247915  0.423040  0.560928   
213  0.582526  0.449800  0.344887  0.648084  0.249213  0.394702  0.497559   
214  0.637684  0.499722  0.337616  0.690683  0.226858  0.410199  0.518084   
215  0.528591  0.453151  0.419430  0.608099  0.348519  0.540139  0.716755   

            7         8         9  ...        91        92        93  \
0  

In [ ]:
df.shape

(216, 101)

In [ ]:
# check for nan values
df.isna().sum()

0             0
1             0
2             0
3             0
4             0
             ..
96            0
97            0
98            0
99            0
N/C_Normal    0
Length: 101, dtype: int64

In [ ]:
df.columns

Index([           0,            1,            2,            3,            4,
                  5,            6,            7,            8,            9,
       ...
                 91,           92,           93,           94,           95,
                 96,           97,           98,           99, 'N/C_Normal'],
      dtype='object', length=101)

In [ ]:
X = df.drop('N/C_Normal', axis=1)
y = df['N/C_Normal']
y.head()

0    0
1    0
2    0
3    0
4    0
Name: N/C_Normal, dtype: int32

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)

In [ ]:
X_train.head()

0         1         2         3         4         5         6   \
117  0.219671  0.174610  0.145977  0.278734  0.105277  0.388147  0.476471   
47   0.335567  0.196353  0.097065  0.413689  0.087901  0.344336  0.457342   
27   0.381793  0.230879  0.130748  0.509708  0.094454  0.325208  0.461303   
59   0.446608  0.428062  0.355256  0.430199  0.241816  0.335200  0.437496   
40   0.503529  0.397826  0.265457  0.607199  0.164204  0.433760  0.586963   

           7         8         9   ...        90        91        92  \
117  0.275036  1.506891  1.746563  ...  0.373210  0.318407  0.144132   
47   0.242717  1.537546  1.645754  ...  0.534452  0.391630  0.234312   
27   0.181154  1.562314  1.840856  ...  0.438801  0.310663  0.153057   
59   0.236318  1.179894  1.444809  ...  0.689632  0.573892  0.201312   
40   0.294950  1.569394  1.817672  ...  0.826620  0.655021  0.180735   

           93        94        95        96        97        98        99  
117  1.670281  0.073720  0.128882  1.306535  0.189869  0.148303  0.122348  
47   1.250842  0.108260  0.086975  1.254973  0.188962  0.133162  0.167043  
27   0.530887  0.149323  0.144372  1.416809  0.180572  0.190383  0.070508  
59   0.658324  0.106453  0.093083  0.883419  0.207201  0.184168  0.099087  
40   0.968595  0.095633  0.160629  1.389370  0.171994  0.227377  0.165386  

[5 rows x 100 columns]

In [ ]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(60, input_dim=100, activation='relu'),
     keras.layers.Dense(1, activation='sigmoid')
])

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=100)

Epoch 1/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.4384 - loss: 0.9216
Epoch 2/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8403 - loss: 0.5497 
Epoch 3/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7965 - loss: 0.4534 
Epoch 4/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8065 - loss: 0.3939 
Epoch 5/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8782 - loss: 0.3400 
Epoch 6/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8780 - loss: 0.3293 
Epoch 7/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8921 - loss: 0.3051 
Epoch 8/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8722 - loss: 0.2920 
Epoch 9/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8816 - loss: 0.2829 
Epoch 10/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8611 - loss: 0.3098 
Epoch 11/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9004 - loss: 0.2507 
Epoch 12/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8914 - loss

In [ ]:
model.evaluate(X_test, y_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9081 - loss: 0.1282  


[0.12380748242139816, 0.9090909361839294]

In [ ]:
y_pred = model.predict(X_test).reshape(-1)
print(y_pred[:10])

# round the values to nearest integer ie 0 or 1
y_pred = np.round(y_pred)
print(y_pred[:10])

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
[1.7941188e-02 4.9497589e-02 3.5581596e-03 3.1483594e-02 6.6637826e-06
 7.8628240e-03 4.7439886e-03 6.5991867e-01 5.0385410e-01 7.5615162e-07]
[0. 0. 0. 0. 0. 0. 0. 1. 1. 0.]


In [ ]:
from sklearn.metrics import confusion_matrix , classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.93      0.93      0.93        30
           1       0.86      0.86      0.86        14

    accuracy                           0.91        44
   macro avg       0.90      0.90      0.90        44
weighted avg       0.91      0.91      0.91        44

